### PR TITLE
split standard and third-party packages imports(fix #30)

### LINKED ISSUE #30: Split standard and third-party packages imports
such as: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/kubeletconfig/fuzzer/fuzzer.go#L19-L31

```go
import (
  "fmt"

  "github.com/a/b"

  "github.com/kasvith/kache/c"
)
```

### PR DESCRIPTION
**Pull request by Chyroc**
## Description

format imports packages

```go
import (
  "a/b"
  "fmt"
  "github.com/kasvith/kache/c"
)
```

to

```go
import (
  "fmt" # standard package

  "a/b" # third-party package

  "github.com/kasvith/kache/c" # self package
)
```

* add `make fmt` to format code
* add `cmd/check_fmt.sh` and `cmd/check_imports.sh` to ci

### CODE REVIEW

**Comment by kasvith** [comment]
Can you add description and issue number too for PR

**Comment by kasvith** [comment]
There seems a problem with Travis

**Comment by Chyroc** [comment]
## Description

format imports packages

```go
import (
  "a/b"
  "fmt"
  "github.com/kasvith/kache/c"
)
```

to

```go
import (
  "fmt"

  "a/b"

  "github.com/kasvith/kache/c"
)
```

* add `make fmt` to format code
* add `cmd/check_fmt.sh` and `cmd/check_imports.sh` to ci

**Comment by kasvith** [comment]
No can you edit the description on the top :)
Would be a help

**Comment by kasvith** [comment]
thanks...is this problem with Travis arise because of godep ? I saw @BigJk had the same problem

**Comment by Chyroc** [comment]
there is no `goimports` command and i install it and i fix it.

**Comment by kasvith** [comment]
thanks @Chyroc

**Pull request merged**
