### PR TITLE
Fix set.Intersection and switch to testify asserts

### PR DESCRIPTION
**Pull request by BigJk**
# Pull Request for issue

https://github.com/kasvith/kache/issues/20

## Description

To show the capabilities of the testify package I ported over the tests. While porting over I noticed that your tests showed that ``set.Intersection`` worked (TestIntersection and TestIntersectionS passed) even if the output of intersection is wrong.

**Current behaviour of intersection** (5f9db9657cba11356777918af935e8ed8f53bf80):

```go
set1 := New()
set2 := New()
set3 := New()

set1.Add([]string{"a", "b", "c", "d"})
set2.Add([]string{"b"})
set3.Add([]string{"a", "b"})

inter := Intersection([]Set{*set1, *set2, *set3})

fmt.Println(inter)
```

prints ``[b b a a]`` but ``[b]`` would be correct if I didn't misunderstand how a intersection works.

### CODE REVIEW

**Comment by BigJk** [comment]
I forgot to port over ``resp_test`` and ``strs_test``. Will fix that!

**Comment by kasvith** [comment]
testsuite should not be removed until all tests are replaced with assert library.

File by file should be converted. Not all at once

**Comment by kasvith** [comment]
Can you try the PR in that way? Its easy to test and merge small PRs

**Comment by BigJk** [comment]
Sure. I will try to split it up :thumbsup:

**Comment by kasvith** [comment]
Thank you

**Pull request closed without merging**
