### PR TITLE
move to dep

### PR DESCRIPTION
**Pull request by Chyroc**
## Description

do

* only install goimports instead of all tools
* if there is no `goimports` command, `./cmd/check_imports.sh` well install it.
* remove `go get -u golang.org/x/tools/...` from .travis.yml and add `dep` install script to .travis.yml
* add `make fmt` to`make all`
* change `make dep` command: from `go get -d ./...` to `dep ensure`

### CODE REVIEW

**Comment by kasvith** [comment]
CI failed

**Comment by Chyroc** [comment]
`dep ensure` only write files to vendor, but not install to `$GOPATH/bin`, so i install `goimports` by `go get` and install vendor by `dep`

**Comment by kasvith** [comment]
@Chyroc did you considere AppVeyor windows build too? if not we can do a seperate PR for that

**Comment by Chyroc** [comment]
Not yet, but we can fix him

**Comment by kasvith** [comment]
We will do a separate PR

**Comment by kasvith** [comment]
thankx @Chyroc

**Pull request merged**
