### PR TITLE
print port number on console #37

### PR DESCRIPTION
**Pull request by nakshay**
# Pull Request for issue 
#37  

## Description

Kache does not print the port number after starting TCP connection
added go routine to print port number on console as well, may be unncessary but will help users.

### CODE REVIEW

**Comment by kasvith** [comment]
Port number will display when you run with `--debug` flag or with `--verbose` flag

**Comment by kasvith** [comment]
Because of confusions we can introduce a loglevel flag which will combine all logging info

**Comment by nakshay** [comment]
OK, closing this PR

**Comment by kasvith** [comment]
klogs can be used to log output to the system....refer how it was used

**Comment by nakshay** [comment]
Okay, Thanks

**Pull request closed without merging**
