### PR TITLE
switched HashMap tests over to testify

### PR DESCRIPTION
**Pull request by BigJk**
# Pull Request for issue

https://github.com/kasvith/kache/issues/20

### CODE REVIEW

**Comment by kasvith** [comment]
I wonder why go get ./... fails to grab the testify

**Comment by Chyroc** [comment]
maybe you can run `dep ensure` to add `github.com/stretchr/testify` to gopkg.lock and then ci well isntall it

**Comment by kasvith** [comment]
@BigJk can you resolve conflicts?

**Comment by kasvith** [comment]
Ok I found the issue, testify need to be fetched as a whole. So `go get ./...` only works for assert package and it causes issue.

We would switch to `dep` to eliminate these issues

**Comment by Chyroc** [comment]
this can be closed

**Comment by kasvith** [comment]
Closed by #50

**Pull request closed without merging**
